### ISSUE TITLE
Is it possible to "Force update" the maps that were created using the RMaps or SQlite3 options?

### ISSUE THREAD

**Issue by Alfonico** [heldersepu/GMapCatcher#435]
Hello.

I haven't been able to check by trial and error the possibility to update SQLite3 maps using the "Force update" tick box.
For the RMaps maps, my experience is that the "Force update" option doesn't seem to work as I expected (see my other post concerning the mix of tiles from different sources when using RMaps)

Please could you tell me if the "Force update" option:
- works for SQlite3 maps
- was supposed to work for the Rmaps maps

Why I'm interrested in the RMaps and SQlite3 maps and I prefer them to the "Files" option?
I can use the RMaps database files as source map for MOBAC, and also as maps in Android mapping applications.
In addition, database files are easier to handle than the individual tile images generated by the option "Files". They are easier to back up, copy and delete (doing these operations on large amount of small tile files takes a long time). They take significantly less disk space (I was obliged to create a dedicated partition with a small cluster size on my disk to avoid loosing ridiculously large amount of disk space with the large amount of small tile files)
I use the SQlite3 maps for GMapcatcher as an alternative to the RMaps due to the unwanted features of the RMaps withing GMapCatcher.

Thanks and regards

**Comment by heldersepu** [comment]
Without checking the code, I'm going to guess and tell you that No,  the "Force update" option probably does not work with SQlite type of storages.

The code is here for all the repos is here:
https://github.com/heldersepu/gmapcatcher/tree/master/gmapcatcher/tilesRepo

If you are concerned with disk space. maybe you should use raw vector data instead of map tiles, see the OsmAnd project:
https://github.com/osmandapp/Osmand

**Comment by Alfonico** [comment]
Hello

Many thanks for the fast replies!

Regards

Alf

**Comment by heldersepu** [comment]
Closing do to lack of input Pull Requests are welcome!
